Stick_It/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.shortcuts import redirect

def redirect_to_login(request):
    return redirect('authentication:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='home'),  # Redirect to login
    path('', include(("authentication.urls",'authentication'), namespace='authentication')),
    path('mainApp/', include('mainApp.urls')),
    path('note/', include(("note.urls",'note'), namespace='note')),
    path("board/",include("board.urls")),
    # path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"
urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name = "login"),
    path('logout/', views.logout_page , name = "logout"),
]

note/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth.views import LogoutView

app_name = "note"
urlpatterns = [
    # path('get_notes/', NoteGetView.as_view(), name='get_notes'),
    path('update_note/<int:pk>/', NoteUpdateView.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', NoteDeleteView.as_view(), name='delete_note'),
    path('base/', LoginService.as_view(), name='base'),
    path('logout/', LogoutView.as_view(next_page="authentication:login"), name="logout"),
    path('home/', HomeView.as_view(), name='home'),
    path('get_notes/<str:noteBoardName>/', NoteGetView.as_view(), name='get_notes'),
    path('<str:board>/', NoteView.as_view(), name='note'),
]

authentication/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, null = True, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='profile_pics')
    birthdate = models.DateField(null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank =True)
    facebook_link = models.TextField(max_length=250, null=True,blank=True)
    facebook_link_hidden = models.BooleanField(null=True, default=True)
    linkedin_link = models.TextField(max_length=250, null=True, blank=True) 
    linkedin_link_hidden = models.BooleanField(null=True, default=True)
    twitter_link = models.TextField(max_length=250, null=True, blank=True)
    twitter_link_hidden = models.BooleanField(null=True, default=True)
    

authentication/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login,logout,authenticate
from django import forms
from datetime import date
from .models import UserProfile


# PROGRAMMER NAME: ELIJAH REI SABAY
# test2user - secondpassword
class StickItLoginForm(forms.Form):
    email = forms.EmailField(
        label = "Email",
        widget=forms.EmailInput(attrs={
            'placeholder': 'Enter email',
            'class': 'form-control',
        })
    )
    password = forms.CharField(
        label="Enter Password", 
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter password',
            'class': 'form-control',
            'height': '40px',
        })
    )

    class Meta:
        model = User
        fields = ['email','password']

class StickItUserCreationForm(UserCreationForm):
    
    # Disables the: 
    # https://stackoverflow.com/questions/78850636/what-is-password-based-authentication-in-the-usercreationform-in-django-and-how
    usable_password = None
    
    email = forms.EmailField(required=True, label="")
    first_name = forms.CharField(max_length=30, required=True, help_text="")
    last_name = forms.CharField(max_length=30, required=True, help_text="")

    class Meta(UserCreationForm.Meta):
        model = User
        # fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name', 'birth_date')
        fields = ('password1', 'password2', 'email', 'first_name', 'last_name')
    
    # This method checks if the email entered by the user already exists in the database.
    def clean_email(self):
        email = self.cleaned_data.get('email') #  Django's initial validation
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with that email already exists.")
        return email
    
    #  This method checks if the first name contains only alphabetic characters.
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name') #  Django's initial validation
        if not first_name.isalpha():
            raise forms.ValidationError("First name should only contain letters.")
        return first_name
    
    # This method checks if the last name contains only alphabetic characters, similar to the clean_first_name method.
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name') #  Django's initial validation
        if not last_name.isalpha():
            raise forms.ValidationError("Last name should only contain letters.")
        return last_name
    
    
    def __init__(self, *args, **kwargs):
        super(StickItUserCreationForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
        """
        Django’s built-in UserCreationForm automatically provides reasonable defaults for help text and validation rules, 
        so you typically don’t need to manually set them unless you have specific requirements.
        e.g. bootstrap design
        """

        # self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        # self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	
        
        # self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['email'].label = ''
        
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['first_name'].label = ''
        
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['last_name'].label = ''
        
    def save(self, commit=True):

        """
        commit=True: Saves the instance to the database immediately.
        commit=False: Creates the instance but does not save it to the database.
        You can make additional modifications before saving it.
        """
        # Create a new user instance but do not save it yet
        user = super().save(commit=False)
        # Access validated data from cleaned_data
        email = self.cleaned_data['email']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        password = self.cleaned_data['password2']

        username = f"{user.first_name}_{user.last_name}"
        if(commit):
            print("Saving user to database")
            user = User.objects.create_user(username=username, email=email, first_name=first_name, last_name=last_name)
            user.set_password(password)
            user.save()
            UserProfile.objects.create(
                user=user,
            )
        return user

authentication/views.py
from django.shortcuts import render
from django.urls import reverse,reverse_lazy
from django.contrib.auth import login,logout,authenticate,get_user_model
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import StickItLoginForm, StickItUserCreationForm

def register_page(request):
        if request.user.is_authenticated:
             return redirect('mainApp:home')
        else:
            form = StickItUserCreationForm()

            if request.method == 'POST':
                form = StickItUserCreationForm(request.POST)
                if form.is_valid():
                    form.save()
                    user = form.cleaned_data.get('first_name')
                    messages.success(request, 'Account was created for ' + user)

                    return redirect('authentication:login')

            context = {'form': form}
            return render(request, 'authentication/register2.html', context)


def login_page(request):
    if request.user.is_authenticated:
         return redirect('mainApp:home')
    
    form = StickItLoginForm(data=request.POST)
    if request.method == 'POST':
        print(request.POST)

        if form.is_valid():
            # email = form.cleaned_data.get('email')
            # password = form.cleaned_data.get('password')
            print("Form is valid")
            user = authenticate(request, username=request.POST['email'], password=request.POST['password'])
            if user is not None:
                # login(request, form.get_user())
                print("User is not none")
                login(request, user)
                return redirect('mainApp:home')
        else:
            print(form.errors)
            messages.info(request, 'Email or password is incorrect')

    context = {'form':form}
    return render(request, 'authentication/login2.html', context)


def logout_page(request):
    logout(request)
    return redirect('authentication:login')

authentication/templates/authentication/login2.html
<!-- PROGRAMMER NAME: -->
<!-- Front-end: MARY KARYLLE DELOS REYES  -->
<!-- Back-end: ELIJAH REI SABAY  -->
{% load static %}
<html>
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Registration Form</title>
      <link rel="stylesheet" href="{%static 'authentication/css/style.css'%}" />
      <!-- <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" /> -->

    </head>
    <body>
        <section class="registration">
            <!-- <h1>HWLO</h1> -->
            <div class="form_container">
          <!-- <i class="uil uil-times form_close"></i> -->
          <!-- Login From -->
          <div class="form login_form">
            <form method="POST">
                {%csrf_token%}
              <h2>Login</h2>
              <div class="input_box">
                <label>Email</label>
                <!-- <input type="email" required /> -->
                 {{form.email}}
              </div>
              
              <div class="input_box" style="margin-top: 40px; margin-bottom:20px">
                <label>Password</label>
                {{form.password}}
              </div>
  
              <button class="button">Login Now</button>
  
              <!-- {% for message in messages %} 
                <p>{{message}}</p>
              {% endfor %} -->

              <div class="login_signup">Don't have an account? <a href="{%url 'authentication:register'%}" id="" style="color: #F0EDED;">Signup</a></div>
            </form>
          </div>

        </div>
      </section>
      <script src="{% static 'js/script.js' %}"></script>
      <script>
        var form_fieds = document.getElementsByTagName('input')
        form_fields[0].placeholder = 'Enter email'
        form_fields[1].placeholder = 'Enter password'

        for (var field in form_fields) {
          form_fields[field].className += ' form-control '
        }
      </script>
    </body>
  </html>
  

authentication/templates/authentication/register2.html
<!-- PROGRAMMER NAME: -->
<!-- Front-end: MARY KARYLLE DELOS REYES  -->
<!-- Back-end: AVRIL NIGEL CHUAY  -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{%static 'css/style.css'%}" />
        <!-- <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" /> -->
        
        <title>Register</title>
    </head>
    <body>
    <section class="registration">
        <!-- <h1>HWLO</h1> -->
        <div class="form_container">
      <!-- <i class="uil uil-times form_close"></i> -->
      <!-- Login From -->
      <div class="form login_form">
        <form method="POST">
            {%csrf_token%}

          <h2>Register</h2>

          <div class="input_box">
            <label>First Name</label>
             {{form.first_name}}
          </div>

          <div class="input_box"style="margin-top: 40px; margin-bottom:20px">
            <label>Last Name</label>
             {{form.last_name}}
          </div>

          <div class="input_box"style="margin-top: 40px; margin-bottom:20px">
            <label>Email</label>
             {{form.email}}
          </div>   

          <!-- <div class="input_box"style="margin-top: 40px; margin-bottom:20px">
            <label>Username</label>
             {{form.username}}
          </div>    -->

          <div class="input_box" style="margin-top: 40px; margin-bottom:20px">
            <label>Password</label>
            {{form.password1}}
          </div>
          
          <div class="input_box" style="margin-top: 40px; margin-bottom:20px">
            <label>Confirm Password</label>
            {{form.password2}}
          </div>

          <!-- <div class="input_box"style="margin-top: 40px;">
            <label>Birthdate</label>
             {{form.birth_date}}
          </div>    -->
          <button class="button" type = 'submit'>Register Now</button>

          {{form.errors}}
          <div class="login_signup">Already have an account? <a href="{%url 'authentication:login'%}" id="" style="color: #F0EDED;">Login</a></div>

         
        </form>
    </div>
    
</div>
</section>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>