Stick_It/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.shortcuts import redirect

def redirect_to_login(request):
    return redirect('authentication:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='home'),  # Redirect to login
    path('', include(("authentication.urls",'authentication'), namespace='authentication')),
    path('mainApp/', include('mainApp.urls')),
    path('note/', include(("note.urls",'note'), namespace='note')),
    path("board/",include("board.urls")),
    # path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

board/urls.py
from django.urls import path
from . import views
# from .views import CreateBoardView, PracticeView

app_name = "board"
urlpatterns = [
    # path('create-board/',CreateBoardView.as_view(),name = "create_table"),
    path('create-board/', views.create_board, name='create_board'),

    # ej changes
    path('home/<int:category_id>/', views.filter_boards_by_category, name='filter_boards_by_category'), 
    path('update/<int:pk>', views.update_board,name='update_board'),
    path('update-progress/<int:pk>', views.update_progress,name='update_progress'),
    path('home/my-board/', views.filter_owner, name='filter_by_owner'),
    # path('home/<slug:category_slug>/', views.filter_boards_by_category, name='filter_boards_by_category'),
    path('response/invite/<int:pk>', views.respond_invite,name="respond_invite"),
    path('response/join/<int:pk>', views.respond_join_request,name="respond_join"),
    # path('join/<int:pk>',views.join_board, name = "join_board"),
    # 

    # path('home/al', views.all_boards, name='all_boards')
    path('my-space/<int:category_id>/', views.filter_boards_by_category, 
         {'template_name': 'mainApp/my_space.html'}, name='filter_boards_by_category_my_space'),
    path('my_board/', views.render_board, name='render_board'),
    path('join-board/<int:board_id>/', views.join_board, name='join_board'),
    # path('board_view/<int:pk>/', views.BoardDetailView.as_view(), name='board_detail'),
    path('board_view/<int:pk>/', views.go_to_effing_board, name='board_detail'),
    
    # for going to effing boards nga katong naay chuy af nga real time shizz
    path('board/go_to_effing_board/<int:pk>', views.go_to_effing_board,name = "note_board")
]

mainApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mainApp'
urlpatterns = [
     path('home/', views.home, name='home'),
     # path('my_space/', views.my_space, name='my_space'),
     path('profile/', views.profile, name='profile'),
     path('my_boards/', views.boards, name='my_boards'),
     path('collaborated_boards/', views.collaborated_boards, name='collaborated_boards'),
     path('profile/edit_profile', views.edit_profile, name='edit_profile'),
     path('profile/user_profile_image', views.profile_image, name='edit_profile_image'),
     path('profile/edit_social_links', views.edit_social_links, name='edit_social_links'),
     path('edit-password/', views.edit_password, name='editPassword'),
     path('account/', views.delete_account, name='deleteAccount'),
     # path('logout/', views.logoutPage , name = "logout"),
     path('board/', include('board.urls', namespace='board')),
]

note/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth.views import LogoutView

app_name = "note"
urlpatterns = [
    # path('get_notes/', NoteGetView.as_view(), name='get_notes'),
    path('update_note/<int:pk>/', NoteUpdateView.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', NoteDeleteView.as_view(), name='delete_note'),
    path('base/', LoginService.as_view(), name='base'),
    path('logout/', LogoutView.as_view(next_page="authentication:login"), name="logout"),
    path('home/', HomeView.as_view(), name='home'),
    path('get_notes/<str:noteBoardName>/', NoteGetView.as_view(), name='get_notes'),
    path('<str:board>/', NoteView.as_view(), name='note'),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.shortcuts import  get_object_or_404
from django.core.exceptions import ValidationError
# from note.models import Note

# Create your models here.

# Programmer Name: Elijah Rei Sabay
# I created this category for searching purposes, feel nako lisod if di sha iseparate entity
class Category(models.Model):
    category_name = models.CharField(max_length=30, unique=True)
    category_description = models.TextField(max_length=100)
    # ej changes

    # for displaying category name in url
    category_slug = models.SlugField(unique=True,editable=False)
    def save(self,*args, **kwargs):
        if not self.category_slug:
            self.category_slug = slugify(self.category_name)
        super().save(*args,**kwargs)
    # 

    def __str__(self):
        return str(self.category_name)
    



class Board(models.Model):
    screenshot = models.ImageField(null=True, blank=True, upload_to='screenshots')
    board_name = models.CharField(max_length=30, unique=True)
    description = models.TextField(max_length=500)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    BOARD_TYPES = (
        ('simple', 'Simple Board'),
        ('project', 'Project Board')
    )
    board_type = models.CharField(max_length=10, choices=BOARD_TYPES, default='simple')
    
    THEME = (
        ('#dddcd7', 'Default (Gray)'),
        ('#e0ecf8', 'Blue'),
        ('#dbeed5', 'Green'),
        ('#fde4e4', 'Pink'),
        ('#f2f4cd', 'Yellow')
    )
    board_theme = models.CharField(max_length=10, choices=THEME, default='#dddcd7')

    VISIBILITY_CHOICES = (
        ('public', 'Public'),
        ('private', 'Private')
    )
    visibility = models.CharField(max_length=7, choices=VISIBILITY_CHOICES, default='public')

    is_active = models.BooleanField(default=True, blank=True)
    is_reported = models.BooleanField(default=False, blank=True)
    date_created = models.DateField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_boards') 
    collaborators = models.ManyToManyField(User, related_name='collaborators')
    users = models.ManyToManyField(User, related_name='boards')
    user_count = models.IntegerField(default=1)
    def clean(self):
        # Sanitize board_name and validate uniqueness
        sanitized_name = slugify(self.board_name)
        print("Sanitized Pason kere",sanitized_name )
        # board = get_object_or_404(Board, board_name=sanitized_name)
        board = None
        try:
            board = Board.objects.get(board_name=sanitized_name)
        except:
             print("went here")
             pass
        if board:
            print(board)
        self.board_name = sanitized_name
        print("Lason kere",sanitized_name )

    def save(self, *args, **kwargs):
        # Ensure clean is called during save
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.board_name


class ProjectBoard(Board):
    progress = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    class Meta:
        db_table = 'project_board'

    def update_progress(self):
        total_notes = self.notes.count()
        completed_notes = self.notes.filter(is_completed=True).count()
        self.progress = (completed_notes / total_notes) * 100 if total_notes > 0 else 0
        self.save()

    def save(self, *args, **kwargs):
        self.board_type = 'project'
        super().save(*args, **kwargs)
        # super(ProjectBoard, self).save(*args, **kwargs)


class SimpleBoard(Board):
    class Meta:
        db_table = 'simple_board'

    def save(self, *args, **kwargs):
        self.board_type = 'simple'
        super().save(*args, **kwargs)


class Notification(models.Model):
    user_sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    user_receiver = models.ForeignKey(User, on_delete=models.CASCADE,related_name='receiver')
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    NOTIF_TYPES = [
        ('invite','Invitation'),
        ('join','Joining'),
        ('remove','Removed'),
        ('accepted','Accepted'),
        ('declined','Declined'),
        
    ]
    notif_type = models.CharField(max_length=10,choices=NOTIF_TYPES)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    has_responded = models.BooleanField(default=False)
    
    def __str__(self):
        return f'Sender: {self.user_sender} Rec: {self.user_receiver} Mess: {self.message} Board: {self.board} Has responded: {self.has_responded}'

board/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Board,Category

class TableCreationForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ["board_name","description","category","board_type","board_theme","visibility"]
    def __init__(self, *args, **kwargs):
        is_update = kwargs.pop('is_update', False)
        super(TableCreationForm, self).__init__(*args, **kwargs)
            
        if is_update:
            self.fields.pop('board_type')


    

    
# https://forum.djangoproject.com/t/how-to-create-dynamic-modals-popups-in-template/8338/2
class CategoryCreationForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["category_name", "category_description"]

    def clean_category_name(self):
        category_name = self.cleaned_data.get('category_name')
        if Category.objects.filter(category_name = category_name).exists():
            raise forms.ValidationError("A category with that name already exists.")
        return category_name

board/templates/board/create_table.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <title>Document</title>
</head>
<body id = "body-sheesh">
    
    <form action="" method = "POST" >
        {%csrf_token%}
        <!-- {{form.board_name}} 
        {{form.category}} -->
        
        <p>Board name</p>{{form.board_name}}
        <p>Board description</p>{{form.description}}
        <p>Pick a caategory</p>
        <div id="category-dropdown">
            {{form.category}}
        </div>
        <div id = "new-cat">
            <input type="button" value = "+">
        </div>
        
        <p>Privacy settings</p>{{form.privacy_settings}}
        
        <input type="submit" value="submit">
    </form>
    <div id = "popup-cat" style = "display: none;">
        
        <h1>Welcome to practice</h1>
        <div id = "categories-list"></div>
        <form id = "cat-form">
            {%csrf_token%}
            {{form2.as_p}}
            <input type="submit" value = "save Cat">
        </form>
    </div>
    <script src="{% static 'board/js/modalscript.js' %}"></script>
</body>
</html>

board/templates/board/my_board.html
<!DOCTYPE html>
{% load static %}
{% load custom_filters %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>STICKIT Board</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />
</head>
<body>
    <div class="toolbar">
        <div class="left-controls">
            <div class="logo">STICKIT</div>
            <button class="back-button"><a href="{% url 'mainApp:home' %}" style="color: black; text-decoration: none;">Back to files</a></button>
        </div>
        <div class="right-controls">
            <div class="circle-indicators" style="padding: {% if count == 1 %}0 0{% else %}0 12px{% endif %};">
                {% if board.user_count >= 5 %}
                    {% if board.users.userprofile.image %}
                    <div class="circle" style="background-image: url({{ board_user.userprofile.image.url }}); background-size: cover; background-position: center;"></div>
                    <div class="circle" style="background-image: url({{ board_user.userprofile.image.url }}); background-size: cover; background-position: center;"></div>
                    <div class="circle" style="background-image: url({{ board_user.userprofile.image.url }}); background-size: cover; background-position: center;"></div>
                    {% else %}
                    <div class="circle">{{ initials }}</div>
                    <div class="circle"></div>
                    <div class="circle"></div>
                    {% endif %}
                    {% if board.user_count > 2 %}
                    <span class="plus-circle">{{ board.user_count }}+</span>
                    {% else %}
                    <span class="plus-circle">{{ board.user_count }}</span>
                    {% endif %}
                {% else %}
                    {% for board_user in board.users.all %}
                        {% if board_user != board.creator %}
                            {% if board_user.userprofile.image %}
                            <div class="circle" style="background-image: url({{ board_user.userprofile.image.url }}); background-size: cover; background-position: center;"></div>
                            {% else %}
                            <div class="circle">{{ board_user }}</div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            {% if board.creator.userprofile.image %}
            <div class="profile-btn" style="background-image: url({{ board.creator.userprofile.image.url }}); background-size: cover; background-position: center;">
            </div>
            {% else %}
            <div class="profile-btn">{{ board.creator}}</div>
            {% endif %}
            {% if user not in board.users.all %}
            <a href="{% url 'board:join_board' board.id %}" class="share-btn join-btn" style="text-decoration: none;">Join Board</a>
            <!-- <button >Join</button> -->
            {% else %}
            <div class="share-btn" style="cursor: none;">{{ board.board_name }}</div>
            {% endif %}
        </div>
    </div>
 
    <div class="board-container">
        <!-- <div class="note blue-note"></div>
        <div class="note pink-note"></div> -->
    </div>
 
    <div class="side-toolbar">
        <div class="edit-note-controls">
            <button class="tool-btn create-note">
                <img src="/media/sticky-note.png" alt="Create-note">
            </button>
        </div>
        <div class="zoom-controls">
            <button class="zoom-out-btn zoom-btn">-</button>
            <span class="zoom-display">100%</span>
            <button class="zoom-in-btn zoom-btn">+</button>
        </div>
    </div>
 
    <div class="general-users-mod" id="general-users-mod">
        <div class="board-users-lbl"><span>Board Users</span></div>
        <div class="board-users-dropdown">
            {% for board_user in board.users.all %}
                {% if board_user != board.creator %}
                    <div class="board-users-dropdown-item"
                        {% if board_user.userprofile.image %}
                        data-image="{{ board_user.userprofile.image.url }}"
                        {% else %}
                        data-first-name="{{ board_user.first_name }}"
                        data-last-name="{{ board_user.last_name }}"
                        {% endif %}
                        data-user-name="{{ board_user.username }}"
                        data-email="{{ board_user.email }}"
                        data-description="{{ board_user.userprofile.description }}"
                        data-facebook="{{ board_user.userprofile.facebook_link }}"
                        data-linkedin="{{ board_user.userprofile.linkedin_link }}"
                        data-twitter="{{ board_user.userprofile.twitter_link }}">
                        {% if board_user.userprofile.image %}
                        <div class="user-list-icon" style="background-image: url({{ board_user.userprofile.image.url }}); background-size: cover; background-position: center;"></div>
                        {% else %}
                        <div class="user-list-icon">{{ board_user|user_initials }}</div>
                        {% endif %}
                        <div class="user-list-name">
                            <span>{{ board_user.username }}</span>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
 
    <div class="general-users-mod admin-users-mod" id="admin-users-mod">
        <div class="board-users-lbl">Board Users</div>
        <div class="board-users-dropdown">
            {% for board_user in board.users.all %}
                {% if board_user != board.creator %}
                    <div class="board-users-dropdown-item">
                        {% if board_user.userprofile.image %}
                        <div class="user-list-icon" style="background-image: url({{ user_profile.image.url }}); background-size: cover; background-position: center;"></div>
                        {% else %}
                        <div class="user-list-icon">{{ board_user|user_initials }}</div>
                        {% endif %}
                        <div class="user-list-name">
                            <span>{{ board_user.username }}</span>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
 
    <div class="profile-modal-overlay">
        <div class="profile-card-modal">
            <div class="close-icon">
                <!-- <img id="close-user-profile" src="/media/white.svg" alt="x-symbol" width="18" height="18"> -->
                <img id="close-user-profile" src="/media/white-close-btn.svg" alt="x-symbol" width="18" height="18">
            </div>
            <div class="image">
                <div class="board-user-profile"></div>
            </div>
            <div class="data dt1">
                <h2 class="board-user-name">Olivia Gomez</h2>
                <span class="board-user-email">olivia.gomez@gmail.com</span>
            </div>
            <div class="data dt2">
                <span class="board-user-description"><em>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel venenatis dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</em></span>
            </div>
            <div class="row socials">
                <a href="" class="board-user-facebook"><div><img src="/media/facebook.svg" alt="" width="30" height="30"></div></a>
                <a href="" class="board-user-linkedin"><div><img src="/media/linkedin.svg" alt="" width="35" height="35"></i></div></a>
                <a href="" class="board-user-twitter"><div><img src="/media/twitter.svg" alt="" width="25" height="25"></i></div></a>
            </div>
        </div>
    </div>
    <script src="{% static 'mainApp/profile_stuff.js' %}"></script>
    <script src="{% static 'scripts.js' %}"></script>
</body>
</html>

board/templates/board/update_board.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>STICKIT|My Space</title>
    <link rel="stylesheet" href="{% static 'mainApp/styles.css' %}">
    <link rel ="stylesheet" href = "{%static 'board/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'mainApp/style.css' %}">
    <!-- <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" /> -->
</head>
<body class="my-space-main-container">
    <header>
        <div class="logo">STICKIT</div>
        <div class="header-icons">
            <button class="create-board-btn">Hello {{request.user}}</button>
            <div class="user-dropdown">
                <div class="user-icon" id="user-icon" onclick="myFunction()">
                    <span class="user-initials">{{ initials }}</span>
                </div>
                <div class="dropdown-menu" id="dropdown-menu">
                    <!-- <a href="#" class="dropdown-item" onclick="openProfileModal()">Profile</a> -->
                    <a href="#" class="dropdown-item">My Space</a>
                    <a   class="dropdown-item" onclick = 'toggleNotificationPopup()'>Notifications</a>

                    <a href="{% url 'authentication:logout' %}" class="dropdown-item">Logout</a>
                </div>
            </div>
        </div>
    </header>

    <main class="my-space">
        <div class="heading-container">
            <!-- <a href="{% url 'mainApp:home' %}"><img src="/media/arrow.png" alt="back-arrow-icon" height="23px" width="23px"></a> -->
            <a href="{% url 'mainApp:home' %}" style="font-size: 15px;">Back to home</a>
            <h1>Update {{board.board_name}}</h1>
        </div>
        <div class="space-content-container">


            <section id="profile-section" class="content-section">
                
                <form action="{% url 'board:update_board' board.id %}" method = "POST">
                    {%csrf_token%}
                    <div class="form-group first-input">
                        <label for="board-namde">Board Name</label>
                        <input type="text" name="board_name" id="board-name" value = "{{board.board_name}}" required>
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select name="category" id="category" onchange="handleCategoryChange()" required>
                            <option value="create-new">Create new...</option>
                            {% for category in categories %}

                                <option value="{{ category.id }}" {%if category.category_name == board.category.category_name%} 
                                    selected  {%endif%}>{{ category.category_name }} </option>
                            {% endfor %}
                        </select>
                        <input type="text" id="new-category" name="new-category" placeholder="Enter new category" style="display: none; margin-top: 10px;">
                    </div>
                    <div class="form-group">
                        <label for="board-description">Board Description</label>
                        <textarea name="description" id="board-description"
                        required> {{board.description}}</textarea>
                    </div>

                    <div class="form-group flex-container" style="margin-bottom: 0;">
                        
                        <div class="form-group">
                            <label for="add">Add users</label>
                            <div class = "add-remove-scrollable">
                                {%for users in add%}
                                <div class="users-checkbox-label">
                                    <input type="checkbox" id="{{ users.id }}" value="{{ users.id }}" name = "add_user">
                                    <label for="{{ users.id }}">{{users.username}}</label>
                                </div>
                                {%endfor%}
                            </div>
                    
                        </div>
                        
                        <div class="form-group">
                            <label for="add">Remove users</label>
                            <div class = "add-remove-scrollable">
                                {%for users in remove%}
                                <div class="users-checkbox-label">
                                    <input type="checkbox" id="{{ users.id }}" value="{{ users.id }}" name = "remove_user">
                                    <label for="{{ users.id }}">{{users.username}}</label>
                                </div>
                                {%endfor%}
                            </div>
                        </div>
                    </div>


                    <div class="form-group flex-container" style="margin-bottom: 0;">
                        <div class="form-group">
                            <label for="visibility">Visibility</label>
                            <select id="visibility" name="visibility" class="visibility-select">
                                <option value="public" {%if board.visibility == "public"%}
                                selected {%endif%}>Public</option>
                                <option value="private" {%if board.visibility == "private"%}
                                selected {%endif%}>Private</option>
                            </select>
                        </div>
                        <!-- <option value="#dddcd7">Default (Gray)</option>
                            <option value="#e0ecf8">Blue</option>
                            <option value="#dbeed5">Green</option>
                            <option value="#fde4e4">Pink</option>
                            <option value="#f2f4cd">Yellow</option> -->
                        <div class="form-group">
                            <label for="theme">Theme</label>
                            <select name="board_theme" id="theme" class="theme-select">
                                <option value="#dddcd7"{%if board.board_theme == "#dddcd7"%}
                                selected {%endif%}>Default (Gray)</option>
                                <option value="#e0ecf8"{%if board.board_theme == "#e0ecf8"%}
                                selected {%endif%}>Blue</option>
                                <option value="#dbeed5"{%if board.board_theme == "#dbeed5"%}
                                selected {%endif%}>Green</option>
                                <option value="#fde4e4"{%if board.board_theme == "#fde4e4"%}
                                selected {%endif%}>Pink</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="board-type">
                                <label>Board Type</label>
                                <select name="board_type" id="board-type" disabled >
                                    <option value="simple" {%if board.board_type == 'simple'%}  
                                    selected{%endif%}>Simple Board</option>
                                    <option value="project" {%if board.board_type == 'project'%}  
                                    selected{%endif%}>Project Board</option>
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="submit-btn">Update</button>

                    </div>
                </form>
            </section>
            
        </div>
    </main>

        <!-- Notifications modal -->
        <div id="notification-popup" class="notification-popup">
            <h3>Notifications</h3>
            <ul id="notification-list">
                <!-- Notifications will be dynamically added here -->
                {%for notifs in notifications%}
                    <li>{{notifs.message}}</li>
                {%endfor%}
            </ul>
        </div>
    <script src="{% static 'board/js/script.js' %}"></script>
    <script src="{% static 'mainApp/scripts.js' %}"></script>
</body>
</html>

board/templates/board/update_table.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
  
  <p><b>Name:</b>  {{board.board_name}}</p>
  <p><b>Description:</b>  {{board.description}}</p>
  <p><b>Owner:</b>  {{board.owner}}</p>
  <p><b>Category:</b>  {{board.category}}</p>
  <p><b>Type:</b>  {{board.board_type}} ps plano nako wala ni kay dapat perm</p>
  <p><b>Theme:</b>  {{board.board_theme}}</p>
  <p><b>Visibility:</b>  {{board.visibility}}</p>
  <p><b>Users:</b> </p>
  {%for users in board.users.all%}
    <p>{{users.username}}</p>
  {%endfor%}

    
  <textarea name="" id="notifs_id"></textarea>

  <form  id = 'update-form'>
    {%csrf_token%}
    <div class="row">
     
      <div class="form-group col-md-4">
        <div class="col">
            <div class="col">
              <label for="inputState">Board Name</label>
              {{form.board_name}}
            </div>

            <div class="col">
              <label for="inputState">Board Name</label>
              {{form.description}}
            </div> 
        </div>
      </div>

      <div class="form-group col-md-4">
        <div class="row">
          <div class="col">
            <div class="form-group col-md-4">
              <label for="inputState">Tyoe</label>
              {{form.board_type}}
            </div>
          </div>
          
          <div class="col">
            <div class="form-group col-md-4">
              <label for="inputState">Theme</label>
              {{form.board_theme}}
            </div>
          </div>
          <div class="col-auto">
            <div class="form-group col-md-4">
              <label for="inputState">Visibility</label>
              {{form.visibility}}
            </div>
          </div>
          
        </div>
        <div class="row">
          <h6>Remove Users</h6>
          {%for users in  board.users.all%}
            <p>{{users.username}}   <input class="form-check-input position-static" type="checkbox" name = "remove_users" id="blankCheckbox" value="{{users.id}}" aria-label="..."></p> 
          {%endfor%}
        </div>
        
      </div>
      <div class="col">
        <label for="">Enter category</label>
        <select name="category" id="id_category" >
          {% for category in form.category.field.queryset %}
              <option value="{{ category.pk }}" {% if category.pk == board.category.id %}selected{% endif %}>
                  {{ category.category_name }}
              </option>
          {% endfor %}
      </select>
        <!-- {{form.new_category}}
        {{form.new_description}} -->
        <div class="col">
          <h6>Add Users</h6>
          {%for users in  form.users.field.queryset%}
            <p>{{users.username}}   <input class="form-check-input position-static" type="checkbox" name = "add_users" id="user_{{users.id}}" value="{{users.id}}" aria-label="..."></p> 
          {%endfor%}
        </div>
      </div>

    </div>
    
    <button type="submit" >Save</button>
  </form>

    <a href="{% url 'mainApp:home'%}">GO HOME</a>
    <!-- <script src="{% static 'board/updateTable.js' %}"></script> -->
     <script>
        const loggedIn = "{{request.user.id}}";
        const user = "{{request.user}}";
        const board_name = "{{board.board_name}}";
        const board = '{{board.id}}'
        const board_desc = "{{board.description}}"
     </script>
    <script src="{% static 'js/notifications.js' %}"></script>

</body>
</html>