Stick_It/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.shortcuts import redirect

def redirect_to_login(request):
    return redirect('authentication:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_login, name='home'),  # Redirect to login
    path('', include(("authentication.urls",'authentication'), namespace='authentication')),
    path('mainApp/', include('mainApp.urls')),
    path('note/', include(("note.urls",'note'), namespace='note')),
    path("board/",include("board.urls")),
    # path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

board/urls.py
from django.urls import path
from . import views
# from .views import CreateBoardView, PracticeView

app_name = "board"
urlpatterns = [
    # path('create-board/',CreateBoardView.as_view(),name = "create_table"),
    path('create-board/', views.create_board, name='create_board'),

    # ej changes
    path('home/<int:category_id>/', views.filter_boards_by_category, name='filter_boards_by_category'), 
    path('update/<int:pk>', views.update_board,name='update_board'),
    path('update-progress/<int:pk>', views.update_progress,name='update_progress'),
    path('home/my-board/', views.filter_owner, name='filter_by_owner'),
    # path('home/<slug:category_slug>/', views.filter_boards_by_category, name='filter_boards_by_category'),
    path('response/invite/<int:pk>', views.respond_invite,name="respond_invite"),
    path('response/join/<int:pk>', views.respond_join_request,name="respond_join"),
    # path('join/<int:pk>',views.join_board, name = "join_board"),
    # 

    # path('home/al', views.all_boards, name='all_boards')
    path('my-space/<int:category_id>/', views.filter_boards_by_category, 
         {'template_name': 'mainApp/my_space.html'}, name='filter_boards_by_category_my_space'),
    path('my_board/', views.render_board, name='render_board'),
    path('join-board/<int:board_id>/', views.join_board, name='join_board'),
    # path('board_view/<int:pk>/', views.BoardDetailView.as_view(), name='board_detail'),
    path('board_view/<int:pk>/', views.go_to_effing_board, name='board_detail'),
    
    # for going to effing boards nga katong naay chuy af nga real time shizz
    path('board/go_to_effing_board/<int:pk>', views.go_to_effing_board,name = "note_board")
]

mainApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mainApp'
urlpatterns = [
     path('home/', views.home, name='home'),
     # path('my_space/', views.my_space, name='my_space'),
     path('profile/', views.profile, name='profile'),
     path('my_boards/', views.boards, name='my_boards'),
     path('collaborated_boards/', views.collaborated_boards, name='collaborated_boards'),
     path('profile/edit_profile', views.edit_profile, name='edit_profile'),
     path('profile/user_profile_image', views.profile_image, name='edit_profile_image'),
     path('profile/edit_social_links', views.edit_social_links, name='edit_social_links'),
     path('edit-password/', views.edit_password, name='editPassword'),
     path('account/', views.delete_account, name='deleteAccount'),
     # path('logout/', views.logoutPage , name = "logout"),
     path('board/', include('board.urls', namespace='board')),
]

note/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth.views import LogoutView

app_name = "note"
urlpatterns = [
    # path('get_notes/', NoteGetView.as_view(), name='get_notes'),
    path('update_note/<int:pk>/', NoteUpdateView.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', NoteDeleteView.as_view(), name='delete_note'),
    path('base/', LoginService.as_view(), name='base'),
    path('logout/', LogoutView.as_view(next_page="authentication:login"), name="logout"),
    path('home/', HomeView.as_view(), name='home'),
    path('get_notes/<str:noteBoardName>/', NoteGetView.as_view(), name='get_notes'),
    path('<str:board>/', NoteView.as_view(), name='note'),
]

mainApp/models.py
from django.db import models

# Create your models here.

board/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Board,Category

class TableCreationForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ["board_name","description","category","board_type","board_theme","visibility"]
    def __init__(self, *args, **kwargs):
        is_update = kwargs.pop('is_update', False)
        super(TableCreationForm, self).__init__(*args, **kwargs)
            
        if is_update:
            self.fields.pop('board_type')


    

    
# https://forum.djangoproject.com/t/how-to-create-dynamic-modals-popups-in-template/8338/2
class CategoryCreationForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["category_name", "category_description"]

    def clean_category_name(self):
        category_name = self.cleaned_data.get('category_name')
        if Category.objects.filter(category_name = category_name).exists():
            raise forms.ValidationError("A category with that name already exists.")
        return category_name

board/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views   .generic import DetailView
from django.contrib.auth import login,authenticate,get_user_model
from .forms import TableCreationForm,CategoryCreationForm
from .models import Category,Board, ProjectBoard, SimpleBoard, Notification
from django.contrib.auth.decorators import login_required
from mainApp.utils import get_user_initials
from django.contrib.auth.models import User
from note.models import Note
from django.urls import reverse
from django.contrib import messages


from authentication.models import UserProfile


# To handle the creation of the new board ---- processes the inout data from modal overlay in mainApp/home.html
@login_required(login_url='authentication:login')
def create_board(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        print("Validating form...")
        post_data = request.POST.copy()

        category_id = request.POST.get('category')
        print(f"This is the category {category_id}")
        # category = Category.objects.get(id=category_id)

        if category_id == 'create-new':
            new_category = request.POST.get('new-category', '').strip()  
            print(f"This is the new category {new_category}")
            if new_category:
                category, created = Category.objects.get_or_create(category_name=new_category)
                # print(f"Category instance: {category}")
                post_data['category'] = category.id
                print(f"Category instance: ")

        else:
            try:
                category = Category.objects.get(id=category_id)
            except Category.DoesNotExist:
                print("Invalid category selected.")
                return render(request, 'board/my_board.html', {'form': form, 'categories': categories})
            
        form = TableCreationForm(post_data)
        # print("this is form:" ,form.data)
 
        if form.is_valid():
            print("Form is valid")
            board_name = form.cleaned_data['board_name']
            description = form.cleaned_data['description']
            board_type = form.cleaned_data['board_type']
            board_theme = form.cleaned_data['board_theme']
            visibility = form.cleaned_data['visibility']

            collaborators = request.POST.getlist('selected_emails[]')
            print(collaborators)

            if board_type == 'project':
                board = ProjectBoard.objects.create(
                    board_name=board_name,
                    description=description,
                    board_type=board_type,
                    board_theme=board_theme,
                    category=category,
                    visibility=visibility,
                    creator=request.user,
                    progress=0  
                )
            elif board_type == 'simple':
                board = SimpleBoard.objects.create(
                    board_name=board_name,
                    description=description,
                    board_type=board_type,
                    board_theme=board_theme,
                    category=category,
                    visibility=visibility,
                    creator=request.user
                )
            else:
                print("Invalid board type.")
                # return render(request, 'board/my_board.html', {'form': form, 'categories': categories})
                return redirect('note:note', board=board.board_name)
            
            print("selected collabs: ",collaborators )
            
            if collaborators:
                for users in collaborators:
                    # print(users)
                    notif = Notification.objects.create(
                        user_sender = request.user,
                        user_receiver = User.objects.get(email = users),
                        board = board,
                        notif_type = 'invite',
                        message = f'You have been invited in {board.board_name}. Accept?')
                    notif.save()
                    # board.users.add(users)
                    

            board.collaborators.add(request.user)
            board.users.add(request.user)
            board.user_count = board.users.count()
            board.save()
            # form.save() 
            # return redirect('board:render_board') 
            return redirect('note:note', board=board.board_name)

        else:
            messages.error(request, "Board created unsuccessfully.")
            return redirect('mainApp:my_boards')
    else:
        form = TableCreationForm()
        form.fields['category'].queryset = categories
    messages.error(request, "Board created unsuccessfully.")
    return redirect('mainApp:my_boards')


@login_required(login_url='authentication:login')
def render_board(request):
    user_initials = get_user_initials(request.user)
    print("user init is: ", user_initials)
    return render(request, 'board/my_board.html', {'user_initials': user_initials})

# ako giusab cuz nahan ko name ang nasa url
# @login_required(login_url='authentication:login')
# def filter_boards_by_category(request, category_id):
#     category = get_object_or_404(Category, id=category_id)
#     boards = Board.objects.filter(category=category)
#     categories = Category.objects.all()  
#     initials = get_user_initials(request.user)

#     return render(request, 'mainApp/home.html', {
#         'initials' : initials,
#         'boards': boards,
#         'categories': categories,
#         'selected_category': category,
#     })

def all_boards(request):
    boards = Board.objects.filter(is_active=True)
    categories = Category.objects.all()
    return render(request, 'board/board_home.html', {'boards': boards, 'categories': categories})


# ej added
# ako giusab cuz nahan ko name ang nasa url
# @login_required(login_url='authentication:login')
# def filter_boards_by_category(request, category_id):
#     category = get_object_or_404(Category, id=category_id)
#     boards = Board.objects.filter(category=category)
#     categories = Category.objects.all()  
#     initials = get_user_initials(request.user)

#     return render(request, 'mainApp/home.html', {
#         'initials' : initials,
#         'boards': boards,
#         'categories': categories,
#         'selected_category': category,
#     })

# ej added
@login_required(login_url='authentication:login')
def filter_owner(request):
    boards = Board.objects.filter(users = request.user, is_Active=True)
    categories = Category.objects.all()  
    notifs = Notification.objects.all()
    initials = get_user_initials(request.user)
    context = {
        'boards': boards,
        'initials' : initials,
        'boards': boards,
        'categories': categories,
        'notifications':notifs,
    }
    return render(request,'mainApp/home.html',context)
    
@login_required
# def filter_boards_by_category(request, category_slug, template_name='mainApp/home.html'):
#     user = request.user 
#     try:
#         user_profile = UserProfile.objects.get(user=user)  
#     except UserProfile.DoesNotExist:
#         user_profile = None 
    
#     # all_categories = Category.objects.all()
#     category = get_object_or_404(Category, category_slug=category_slug)
#     if template_name == 'mainApp/home.html':
#         boards = Board.objects.filter(category=category)
#         categories = Category.objects.all()
#         count = boards.count()
#     else:
#         boards = Board.objects.filter(creator=user, category=category)
#         categories = Category.objects.filter(board__creator=user).distinct()
#         count = boards.count()
#     initials = get_user_initials(request.user)
#     notifs = Notification.objects.all()

#     return render(request, template_name, {
#         'initials' : initials,
#         'user_profile': user_profile,
#         'boards': boards,
#         'count' : count,
#         # 'all_categories' : all_categories,
#         'categories': categories,
#         'selected_category': category,
#         'notifications':notifs,
#     })

def filter_boards_by_category(request, category_id,template_name='mainApp/home.html'):
    user = request.user 
    try:
        user_profile = UserProfile.objects.get(user=user)  
    except UserProfile.DoesNotExist:
        user_profile = None 
    
    # all_categories = Category.objects.all()
    category = get_object_or_404(Category, pk=category_id)
    if template_name == 'mainApp/home.html':
        boards = Board.objects.filter(category=category, is_active=True).exclude(users = request.user)
        categories = Category.objects.all()
        count = boards.count()
    else:
        boards = Board.objects.filter(creator=user, category=category, is_active=True)
        categories = Category.objects.filter(board__creator=user).distinct().exclude(users = request.user)
        count = boards.count()
    initials = get_user_initials(request.user)
    notifs = Notification.objects.all()

    return render(request, template_name, {
        'initials' : initials,
        'user_profile': user_profile,
        'boards': boards,
        'count' : count,
        # 'all_categories' : all_categories,
        'categories': categories,
        'selected_category': category,
        'notifications':notifs,
    })

@login_required
def update_board(request,pk):
    if request.method == 'POST':
        form = TableCreationForm(request.POST,is_update =True)
        if form.is_valid():
            # print(form.data)
            board = Board.objects.get(pk=pk)
   

            board.board_name = form.cleaned_data['board_name']
            board.category = form.cleaned_data['category']
            board.description = form.cleaned_data['description']
            board.board_theme = form.cleaned_data['board_theme']

mainApp/templates/mainApp/boards.html
{% extends 'mainApp/base.html' %}
{% block content %}
{% if messages %}
    <div class="board-alert-container">
        {% for message in messages %}
            <div class="board-alert board-alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}

<section class="boards-header">
    <div class="board-tabs">
        <a href="{% url 'mainApp:my_boards' %}"><button class="tab-button user-boards-sect active">My Boards</button></a>
        <a href="{% url 'mainApp:collaborated_boards' %}"><button class="tab-button shared-boards-sect">Collaborated Boards</button></a>
    </div>
    <!-- <div class="filters">
        <select class="filter-dropdown">
            <option>Visibility</option>
            <option>Public</option>
            <option>Private</option>
        </select>
        <select class="filter-dropdown">
            <option>Board Type</option>
            <option>Project</option>
            <option>Simple</option>
        </select>
    </div> -->
</section>

<section class="board-list home-boards b1-board-list">
    {% for board in boards %}
        <a href="{% url 'board:note_board' board.id %}" class="board-preview" style="background-color: {{ board.board_theme }};">
            <div class="board-header">
                <h2>{{ board.board_name }}</h2>
                <img class="ellipsis" src="/media/option.svg" alt="vertical-dots" width="12" height="12">
                <!-- <div class="ellipsis">...</div> -->
            </div>
            <div class="board-content">
                <p class="creator">Created by {{ board.creator.username }}</p>
                <p class="updated-time">Last updated {{ board.timestamp }}</p>
                <div class="ca-vi-container">
                    <div class="board-category">{{ board.category.category_name }}</div>
                    {% if board.visibility == 'public' %}
                    <p class="collaborator">Public Board</p>
                    {% else %}
                    <p class="collaborator">Private Board</p>
                    {% endif %}
                </div>
                {% if board.board_type == 'project' %}
                    {%for project in projectboards%}
                    <!--HEREEEEEEEEEEEE DONE-->
                    {%if project.id == board.id%}
                <!-- <div class="progress-container" style="border-top: none;">
                    <div class="progress-bar">
                    </div>
                    <span data-width="90%">{{project.progress}}%</span>
                </div> -->
                <div class="progress-container" style="border-top: none;">
                    <div id="myProgress">

                        <div id="myBar" 
                                 style="width: {{ project.progress }}%;">
                        </div>
                    </div>
                    <span>{{ project.progress }}%</span>
                </div>
                
                
                {%endif%}
                {%endfor%}
                {% endif %}
            </div>
        </a>
    {% endfor %}

</section>

{% endblock %}

mainApp/templates/mainApp/profile.html
{% extends 'mainApp/base.html' %}

{% block content %}
<section class="profile-section">
    <div class="profile-card  main-profile-card">
        <form method="POST" action="{% url 'mainApp:edit_profile' %}">
            {% csrf_token %}
            <div class="profile-info">
                <div class="profile-image">
                    {% if user_profile.image %} 
                    <div class="profile-circle" style="background-image: url({{ user_profile.image.url }}); background-size: cover; background-position: center;">
                        <i class="fas fa-pen edit-icon" onclick="openEditProfPicModal()"></i>
                    </div>
                    {% else %} 
                    <div class="profile-circle" style="background: linear-gradient(90deg, #dededc, #a9a9ad);">
                        <span>{{ initials }}</span>
                        <i class="fas fa-pen edit-icon" onclick="openEditProfPicModal()"></i>
                    </div>
                    {% endif %}
                    
                    <h2>{{ user.username }}</h2>
                    <span>Joined last {{ user.date_joined }}</span>
                    {% if user_profile.description == None or user_profile.description == '' %}
                    <input id="description-input" name="description" type="text" placeholder="Add short self-description" class="profile-input short-bio-input"/>
                    {% else %}
                    <input id="description-input" name="description" type="text" value="{{ user_profile.description }}"class="profile-input short-bio-input"/>
                    {% endif %}
                </div>
                <div class="profile-details">
                    <h3>Profile Details</h3>
                    <label for="first_name">First Name*</label>
                    <input class="profile-input" id="firstname-input" name="first_name" type="text" value="{{ user.first_name }}" required/>

                    <label for="last_name">Last Name*</label>
                    <input class="profile-input" id="lastname-input" name="last_name" type="text" value="{{ user.last_name }}" required/>
                    
                    <label for="email">Email*</label>
                    <input class="profile-input" id="email-input" name="email" type="email" value="{{ user.email }}" required/>
                    
                    <label for="birthdate">Birthdate</label>
                    {% if user_profile.birthdate == None or user_profile.birthdate == '' %}
                    <input class="profile-input" id="birthdate-input" name="birthdate" type="date" value="" placeholder="Add birthdate"/>
                    {% else %}
                    <input class="profile-input" id="birthdate-input" name="birthdate" type="date" value="{{ user_profile.birthdate|date:'Y-m-d' }}" />
                    {% endif %}
                </div>
            </div>
            <button type="submit" id="p1-update-btn" class="edit-profile-btn">Update</button>    
        </form>
    </div>
    <div class="profile-card social-profile-card" >
        <form method="POST" action="{% url 'mainApp:edit_social_links' %}"> 
            {% csrf_token %}
            <div class="profile-details social-links-details">
                <h3>Social Links</h3>
                <label for="facebook_link">Facebook</label>
                {% if user_profile.facebook_link == None or user_profile.facebook_link == '' %}
                <input class="socials-input" name="facebook_link" type="text" id="facebook" value="" placeholder="Add Facebook link"/>
                {% else %}
                <input class="socials-input" name="facebook_link" type="text" id="facebook" value="{{ user_profile.facebook_link }}" />
                {% endif %}
                
                <label for="linkedin_link">LinkedIn</label>
                {% if user_profile.linkedin_link == None or user_profile.linkedin_link == '' %}
                <input class="socials-input" name="linkedin_link" type="text" id="linkedin" value="" placeholder="Add LinkedIn link"/>
                {% else %}
                <input class="socials-input" name="linkedin_link" type="text" id="linkedin" value="{{ user_profile.linkedin_link }}" />
                {% endif %}
                
                <label for="twitter_link">Twitter</label>
                {% if user_profile.twitter_link == None or user_profile.twitter_link == '' %}
                <input class="socials-input" name="twitter_link" type="text" id="twitter" value="" placeholder="Add Twitter link"/>
                {% else %}
                <input class="socials-input" name="twitter_link" type="text" id="twitter" value="{{ user_profile.twitter_link }}" />
                {% endif %}
                <!-- <div class="social-icons">
                    <a href="#"><i class="fab fa-facebook"></i></a>
                    <a href="#"><i class="fab fa-linkedin"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                </div> -->
                
            </div>
            <button type="submit" id="p2-update-btn" class="edit-profile-btn update-btn-socials">Update</button>    
        </form>
    </div>
</section>

<div class="profile-pic-form-mod">
    <form method="POST" action="{% url 'mainApp:edit_profile_image' %}" enctype="multipart/form-data" >
        {% csrf_token %}
        <img class="pp-modal-close" src="/media/x-close.svg" alt="x-symbol" width="16" height="16" onclick="closeEditProfPicModal()">
        <input type="file" name="image" accept="image/*" />
        <!-- <button class="remove-pp-btn">Remove Profile Pic</button> -->
        <!-- <button type="submit" class="upload-pp-btn">Upload</button> -->
        <button type="submit" name="action" value="upload" class="upload-pp-btn">Upload</button>
        <button type="submit" name="action" value="remove" class="remove-pp-btn">Remove Profile Pic</button>
    </form>
</div>

{% endblock %}